2023-08-24 14:15:49,315 INFO    StreamThr :3730 [internal.py:wandb_internal():86] W&B internal server running at pid: 3730, started at: 2023-08-24 14:15:49.315163
2023-08-24 14:15:49,316 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: status
2023-08-24 14:15:49,318 INFO    WriterThread:3730 [datastore.py:open_for_write():85] open: /Users/gabdu45/PycharmProjects/segmentationCryoEM/wandb/run-20230824_141549-3i9liejb/run-3i9liejb.wandb
2023-08-24 14:15:49,318 DEBUG   SenderThread:3730 [sender.py:send():379] send: header
2023-08-24 14:15:49,357 DEBUG   SenderThread:3730 [sender.py:send():379] send: run
2023-08-24 14:15:54,384 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:15:59,404 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:16:04,425 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:16:09,451 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:16:14,474 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:16:16,476 INFO    SenderThread:3730 [dir_watcher.py:__init__():211] watching files in: /Users/gabdu45/PycharmProjects/segmentationCryoEM/wandb/run-20230824_141549-3i9liejb/files
2023-08-24 14:16:16,476 INFO    SenderThread:3730 [sender.py:_start_run_threads():1121] run started: 3i9liejb with start time 1692879349.315349
2023-08-24 14:16:16,477 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: status_report
2023-08-24 14:16:16,479 DEBUG   SenderThread:3730 [sender.py:send_request():406] send_request: summary_record
2023-08-24 14:16:16,481 INFO    SenderThread:3730 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-08-24 14:16:16,495 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: check_version
2023-08-24 14:16:16,495 DEBUG   SenderThread:3730 [sender.py:send_request():406] send_request: check_version
2023-08-24 14:16:17,480 INFO    Thread-12 :3730 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/gabdu45/PycharmProjects/segmentationCryoEM/wandb/run-20230824_141549-3i9liejb/files/wandb-summary.json
2023-08-24 14:16:21,503 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: status_report
2023-08-24 14:16:21,529 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: run_start
2023-08-24 14:16:21,563 DEBUG   HandlerThread:3730 [system_info.py:__init__():31] System info init
2023-08-24 14:16:21,563 DEBUG   HandlerThread:3730 [system_info.py:__init__():46] System info init done
2023-08-24 14:16:21,563 INFO    HandlerThread:3730 [system_monitor.py:start():181] Starting system monitor
2023-08-24 14:16:21,564 INFO    SystemMonitor:3730 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-08-24 14:16:21,564 INFO    HandlerThread:3730 [system_monitor.py:probe():201] Collecting system info
2023-08-24 14:16:21,566 INFO    SystemMonitor:3730 [interfaces.py:start():190] Started cpu monitoring
2023-08-24 14:16:21,566 DEBUG   HandlerThread:3730 [system_info.py:probe():195] Probing system
2023-08-24 14:16:21,566 INFO    SystemMonitor:3730 [interfaces.py:start():190] Started disk monitoring
2023-08-24 14:16:21,567 INFO    SystemMonitor:3730 [interfaces.py:start():190] Started memory monitoring
2023-08-24 14:16:21,567 INFO    SystemMonitor:3730 [interfaces.py:start():190] Started network monitoring
2023-08-24 14:16:21,590 DEBUG   HandlerThread:3730 [system_info.py:_probe_git():180] Probing git
2023-08-24 14:16:21,644 DEBUG   HandlerThread:3730 [system_info.py:_probe_git():188] Probing git done
2023-08-24 14:16:21,644 DEBUG   HandlerThread:3730 [system_info.py:probe():240] Probing system done
2023-08-24 14:16:21,644 DEBUG   HandlerThread:3730 [system_monitor.py:probe():210] {'os': 'macOS-10.16-x86_64-i386-64bit', 'python': '3.10.4', 'heartbeatAt': '2023-08-24T12:16:21.566594', 'startedAt': '2023-08-24T12:15:49.305179', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/gabdu45/PycharmProjects/segmentationCryoEM/main.py', 'codePath': 'main.py', 'git': {'remote': 'https://github.com/Gabriel-Ducrocq/segmentationCryoEM.git', 'commit': 'fe93329623f38b36548bbe2e440ae49edb50cb1e'}, 'email': 'gabrielducrocq.maths@gmail.com', 'root': '/Users/gabdu45/PycharmProjects/segmentationCryoEM', 'host': 'mac00987', 'username': 'gabdu45', 'executable': '/Users/Shared/anaconda3/envs/conformationalLatent/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 2400, 'min': 2400, 'max': 2400}, 'cpu_freq_per_core': [{'current': 2400, 'min': 2400, 'max': 2400}], 'disk': {'total': 460.4317207336426, 'used': 11.049102783203125}, 'memory': {'total': 32.0}}
2023-08-24 14:16:21,644 INFO    HandlerThread:3730 [system_monitor.py:probe():211] Finished collecting system info
2023-08-24 14:16:21,644 INFO    HandlerThread:3730 [system_monitor.py:probe():214] Publishing system info
2023-08-24 14:16:21,644 DEBUG   HandlerThread:3730 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-08-24 14:16:21,645 DEBUG   HandlerThread:3730 [system_info.py:_save_pip():67] Saving pip packages done
2023-08-24 14:16:21,645 DEBUG   HandlerThread:3730 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-08-24 14:16:22,502 INFO    Thread-12 :3730 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/gabdu45/PycharmProjects/segmentationCryoEM/wandb/run-20230824_141549-3i9liejb/files/conda-environment.yaml
2023-08-24 14:16:22,503 INFO    Thread-12 :3730 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/gabdu45/PycharmProjects/segmentationCryoEM/wandb/run-20230824_141549-3i9liejb/files/requirements.txt
2023-08-24 14:16:23,614 DEBUG   HandlerThread:3730 [system_info.py:_save_conda():86] Saving conda packages done
2023-08-24 14:16:23,650 INFO    HandlerThread:3730 [system_monitor.py:probe():216] Finished publishing system info
2023-08-24 14:16:23,665 DEBUG   SenderThread:3730 [sender.py:send():379] send: files
2023-08-24 14:16:23,665 INFO    SenderThread:3730 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2023-08-24 14:16:23,670 DEBUG   SenderThread:3730 [sender.py:send():379] send: telemetry
2023-08-24 14:16:23,671 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: stop_status
2023-08-24 14:16:23,672 DEBUG   SenderThread:3730 [sender.py:send_request():406] send_request: stop_status
2023-08-24 14:16:24,520 INFO    Thread-12 :3730 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/gabdu45/PycharmProjects/segmentationCryoEM/wandb/run-20230824_141549-3i9liejb/files/conda-environment.yaml
2023-08-24 14:16:24,520 INFO    Thread-12 :3730 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/gabdu45/PycharmProjects/segmentationCryoEM/wandb/run-20230824_141549-3i9liejb/files/wandb-metadata.json
2023-08-24 14:16:24,520 INFO    Thread-12 :3730 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/gabdu45/PycharmProjects/segmentationCryoEM/wandb/run-20230824_141549-3i9liejb/files/output.log
2023-08-24 14:16:26,540 INFO    Thread-12 :3730 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/gabdu45/PycharmProjects/segmentationCryoEM/wandb/run-20230824_141549-3i9liejb/files/output.log
2023-08-24 14:16:28,506 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:28,508 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:28,509 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:28,511 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:28,512 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:28,513 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:28,516 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:28,516 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:28,696 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:16:33,711 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:16:36,546 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:36,548 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:36,549 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:36,552 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:36,553 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:36,555 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:36,556 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:36,558 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: partial_history
2023-08-24 14:16:37,678 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-24 14:16:41,897 INFO    SenderThread:3730 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/Shared/anaconda3/envs/conformationalLatent/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fab78566a10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fab78566a10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 323, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/gabdu45/.local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fab78566a10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-08-24 14:16:42,696 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:16:47,720 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:16:52,739 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:16:57,764 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:17:02,788 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:17:07,802 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:17:12,820 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:17:17,842 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:17:21,573 DEBUG   SystemMonitor:3730 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-08-24 14:17:22,644 WARNING FileStreamThread:3730 [file_stream.py:request_with_retry():666] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=60.0). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7fab8a7a44c0>>, timeout=60.0), args: ('https://api.wandb.ai/files/gabriel-ducrocq/segmentation_protein/3i9liejb/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{}']}}, 'dropped': 0}}
2023-08-24 14:17:22,865 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:17:24,689 WARNING FileStreamThread:3730 [file_stream.py:request_with_retry():666] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/gabriel-ducrocq/segmentation_protein/3i9liejb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fab382080d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7fab8a7a44c0>>, timeout=60.0), args: ('https://api.wandb.ai/files/gabriel-ducrocq/segmentation_protein/3i9liejb/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{}']}}, 'dropped': 0}}
2023-08-24 14:17:27,880 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:17:29,616 WARNING FileStreamThread:3730 [file_stream.py:request_with_retry():666] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/gabriel-ducrocq/segmentation_protein/3i9liejb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fab7848d090>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7fab8a7a44c0>>, timeout=60.0), args: ('https://api.wandb.ai/files/gabriel-ducrocq/segmentation_protein/3i9liejb/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{}']}}, 'dropped': 0}}
2023-08-24 14:17:32,900 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:17:37,923 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:17:39,585 WARNING FileStreamThread:3730 [file_stream.py:request_with_retry():666] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/gabriel-ducrocq/segmentation_protein/3i9liejb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fab784e9390>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7fab8a7a44c0>>, timeout=60.0), args: ('https://api.wandb.ai/files/gabriel-ducrocq/segmentation_protein/3i9liejb/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{}']}}, 'dropped': 0}}
2023-08-24 14:17:42,941 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:17:47,962 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:17:52,980 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:17:56,578 WARNING FileStreamThread:3730 [file_stream.py:request_with_retry():666] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/gabriel-ducrocq/segmentation_protein/3i9liejb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fab784e9150>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7fab8a7a44c0>>, timeout=60.0), args: ('https://api.wandb.ai/files/gabriel-ducrocq/segmentation_protein/3i9liejb/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{}']}}, 'dropped': 0}}
2023-08-24 14:17:58,005 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:18:03,025 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:18:08,042 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:18:13,069 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:18:18,090 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:18:23,110 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:18:28,132 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:18:33,159 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:18:38,180 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:18:43,199 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:18:48,220 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:18:53,241 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:18:58,260 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:19:03,286 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:19:08,315 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:19:13,343 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:19:18,366 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:19:23,392 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:19:28,412 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:19:29,149 WARNING FileStreamThread:3730 [file_stream.py:request_with_retry():666] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/gabriel-ducrocq/segmentation_protein/3i9liejb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fab785660b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7fab8a7a44c0>>, timeout=60.0), args: ('https://api.wandb.ai/files/gabriel-ducrocq/segmentation_protein/3i9liejb/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{}']}}, 'dropped': 0}}
2023-08-24 14:19:33,438 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:19:38,455 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:19:43,477 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:19:48,501 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:19:53,521 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:19:58,541 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:20:03,554 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:20:08,577 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:20:13,600 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
2023-08-24 14:20:18,616 DEBUG   HandlerThread:3730 [handler.py:handle_request():144] handle_request: keepalive
